# Generated by Django 5.1.4 on 2025-01-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbsrjobs',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.TextField(),
        ),
    ]
